name: Recipes CI
on: [push, workflow_dispatch]
env:
  FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
  REGISTRY: registry.fly.io/hufi-mimi-recipes
  TAG: ${{ github.sha }}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop .#lint -c just lint
  build-and-deploy:
    needs: lint
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop -c just build
      - run: nix develop -c just push-image
      - run: nix develop -c just deploy
