name: Recipes CI
on: [push, workflow_dispatch]
env:
  FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
  REGISTRY: registry.fly.io/hufi-mimi-recipes
  TAG: ${{ github.sha }}
jobs:
  ci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      # runs `cargo check`, `cargo test` and `cargo build`
      - run: nix build .#cooklint
      - run: ./result/cooklint --version
