name: Recipes CI
on: [push, workflow_dispatch]
env:
  FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
  REGISTRY: registry.fly.io/hufi-mimi-recipes
  TAG: ${{ github.sha }}
jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop --command just ci

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .#cooklint
      - run: ./result/bin/cooklint --version
